# Generated by Django 5.0.4 on 2024-04-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moshina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=60)),
                ('car_model', models.CharField(max_length=40)),
                ('car_price', models.CharField(max_length=60)),
                ('car_company', models.CharField(max_length=60)),
            ],
        ),
    ]
