# Generated by Django 5.0.4 on 2024-04-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clent_name', models.CharField(max_length=70)),
                ('clent_last_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60)),
                ('user_last_name', models.CharField(max_length=60)),
                ('user_phone_number', models.IntegerField()),
                ('user_email', models.CharField(max_length=60)),
            ],
        ),
    ]
